version: '3.8'
services:
  sales-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318/v1/traces # Cambia si está en otra red
      - OTEL_SERVICE_NAME=sales-api
